[0.110s] Invoking command in '/home/dareum/ME454/ros2_ws/build/coin_rolling_msg': CMAKE_PREFIX_PATH=/opt/ros/humble CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake /home/dareum/ME454/ros2_ws/src/coin_rolling_msg -DCMAKE_INSTALL_PREFIX=/home/dareum/ME454/ros2_ws/install/coin_rolling_msg
[0.319s] -- Found ament_cmake: 1.3.8 (/opt/ros/humble/share/ament_cmake/cmake)
[0.540s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.550s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.555s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.840s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.869s] -- Found geometry_msgs: 4.2.3 (/opt/ros/humble/share/geometry_msgs/cmake)
[1.092s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[1.092s]   execute_process(/home/dareum/anaconda3/envs/mujoco_py/bin/python3 -m
[1.092s]   rosidl_adapter --package-name coin_rolling_msg --arguments-file
[1.092s]   /home/dareum/ME454/ros2_ws/build/coin_rolling_msg/rosidl_adapter__arguments__coin_rolling_msg.json
[1.092s]   --output-dir
[1.092s]   /home/dareum/ME454/ros2_ws/build/coin_rolling_msg/rosidl_adapter/coin_rolling_msg
[1.092s]   --output-file
[1.092s]   /home/dareum/ME454/ros2_ws/build/coin_rolling_msg/rosidl_adapter/coin_rolling_msg.idls)
[1.092s]   returned error code 1:
[1.092s] 
[1.093s]   Traceback (most recent call last):
[1.093s] 
[1.093s]     File "/home/dareum/anaconda3/envs/mujoco_py/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1.093s]       return _run_code(code, main_globals, None,
[1.093s]     File "/home/dareum/anaconda3/envs/mujoco_py/lib/python3.8/runpy.py", line 87, in _run_code
[1.093s]       exec(code, run_globals)
[1.093s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.093s]       sys.exit(main())
[1.093s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[1.093s]       abs_idl_file = convert_to_idl(
[1.093s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 18, in convert_to_idl
[1.093s]       from rosidl_adapter.msg import convert_msg_to_idl
[1.093s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 16, in <module>
[1.093s]       from rosidl_adapter.resource import expand_template
[1.093s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 19, in <module>
[1.093s]       import em
[1.093s] 
[1.093s]   ModuleNotFoundError: No module named 'em'
[1.093s] 
[1.094s] Call Stack (most recent call first):
[1.094s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.094s]   CMakeLists.txt:23 (rosidl_generate_interfaces)
[1.094s] 
[1.094s] [0m
[1.094s] -- Configuring incomplete, errors occurred!
[1.094s] See also "/home/dareum/ME454/ros2_ws/build/coin_rolling_msg/CMakeFiles/CMakeOutput.log".
